In [33]:
import numpy as np
# 1 & 3 & -1 & 0 \\
# 2 & 1 & 0 & -1 \\
# 1 & 2 & 0 & 0 \\
# 3 & 1 & 0 & 0 \\
B = [[1, 3, -1, 0],
     [2, 1, 0, -1],
     [1, 2, 0, 0],
     [3, 1, 0, 0]]
b = [15, 10, 40, 60]

# 0 & 0 \\
# 0 & 0 \\ 
# 1 & 0 \\
# 0 & 1 \\
N = [[0, 0],
     [0, 0],
     [1, 0],
     [0, 1]]

np.linalg.solve(B, b)

array([16., 12., 37., 34.])

In [34]:
cN = [0, 0]
cB = [-1, -1, 0, 0]

cN - cB @ np.linalg.inv(B) @ N

array([0.4, 0.2])

In [24]:
dN = [1, 0]
dB = - np.linalg.inv(B) @ N @ dN

xB = np.linalg.solve(B, b)

theta_list = - xB / dB
theta_list

array([ 60.   ,  -1.875, -90.   ,  12.   ])

In [26]:
dB

array([-0.33333333,  2.66666667,  0.33333333, -1.66666667])

In [19]:
np.round(xB + 5 * dB, 0)

array([20., 30., 20., -0.])

In [29]:
xB_new = xB + 12 * dB
xB_new

array([16., 37., 34.,  0.])